name: Python Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      USER_BASE_BIN: "$(python -m site --user-base)/bin"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
        echo "USER_BASE_BIN=${USER_BASE_BIN}" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        # If you have a requirements.txt file, install dependencies
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi

    - name: Lint code
      run: |
        pip install flake8
        flake8 sample.py

    - name: Run tests
      run: |
        python -m unittest discover -v
